openapi: 3.0.1
info:
  title: '@jupiterone/graph-cobalt'
  description: A graph conversion tool for https://cobalt.io/
  x-cortex-git:
    github:
      repository: JupiterOne/graph-cobalt
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-tag: '@jupiterone/graph-cobalt'
  x-cortex-service-groups:
    - tier-4
